### ISSUE TITLE
TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by edgarasben** [react-syntax-highlighter/react-syntax-highlighter#502]
**Describe the bug**
Trying out a simple component in NextJS 13:

```tsx
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'

export default function Test2() {
    const codeString = '(num) => num + 1'
    return <SyntaxHighlighter language="javascript">{codeString}</SyntaxHighlighter>
}
```

And I am getting this error:

```
error - node_modules/@babel/runtime/helpers/inherits.js (4:10) @ _inherits
error - TypeError: Super expression must either be null or a function
    at _inherits (webpack-internal:///(sc_server)/./node_modules/@babel/runtime/helpers/inherits.js:5:15)
    at eval (webpack-internal:///(sc_server)/./node_modules/react-syntax-highlighter/dist/cjs/async-syntax-highlighter.js:45:35)
    at _default (webpack-internal:///(sc_server)/./node_modules/react-syntax-highlighter/dist/cjs/async-syntax-highlighter.js:164:6)
    at eval (webpack-internal:///(sc_server)/./node_modules/react-syntax-highlighter/dist/cjs/light-async.js:50:55)
    at (sc_server)/./node_modules/react-syntax-highlighter/dist/cjs/light-async.js (/Users/me/Sites/me/.next/server/app/test2/page.js:3339:1)
    at __webpack_require__ (/Users/me/Sites/me/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./node_modules/react-syntax-highlighter/dist/cjs/index.js:55:42)
    at (sc_server)/./node_modules/react-syntax-highlighter/dist/cjs/index.js (/Users/me/Sites/me/.next/server/app/test2/page.js:3306:1)
    at __webpack_require__ (/Users/me/Sites/me/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(sc_server)/./app/test2/page.tsx:6:82) {
  type: 'TypeError',
  page: '/test2'
}
```

**To Reproduce**
1. Install NextJS 13.0.7
2. Install react-syntax-highlighter 15.5.0
3. Add a simple page Test
4. Add a code I posted above
5. See error I posted above

**Expected behavior**
-

**Screenshots**
-

**Desktop (please complete the following information):**
 - mac OS
 - Browser: Arc - Version 0.81.1 (36547)
 - Chromium Engine Version 108.0.5359.125

**Comment by edgarasben** [comment]
Found a problem. I forgot to use `'use client'` in NextJS 13.
