### ISSUE TITLE
Not working on Storybook

### ISSUE THREAD

**Issue by ryota-murakami** [react-syntax-highlighter/react-syntax-highlighter#522]
**Describe the bug**
`yarn storybook` doesn't and show following error in console.

```csharp
✘ [ERROR] Invalid command: on-resolve [plugin JavaScript plugins]
    node_modules/esbuild/lib/main.js:728:12:
      728 │       throw new Error(`Invalid command: ` + request.command);
          ╵             ^
   at handleRequest .handleRequest (/Users/ryota.murakami/laststance/nsx/node_modules/esbuild/lib/main.js:728:13 undefined)
   at handleIncomingPacket .handleIncomingPacket (/Users/ryota.murakami/laststance/nsx/node_modules/esbuild/lib/main.js:745:7 undefined)
   at Socket.readFromStdout (/Users/ryota.murakami/laststance/nsx/node_modules/esbuild/lib/main.js:673:7 undefined)
   at Socket.emit (node:events:513:28 undefined)
   at addChunk .addChunk (node:internal/streams/readable:324:12 undefined)
   at readableAddChunk .readableAddChunk (node:internal/streams/readable:297:9 undefined)
   at Readable.push (node:internal/streams/readable:234:10 undefined)
   at Pipe.onStreamRead (node:internal/stream_base_commons:190:23 undefined)
  The plugin "JavaScript plugins" was triggered by this import
    node_modules/react-syntax-highlighter/dist/esm/async-languages/prism.js:1376:4:
      1376 │     "refractor/lang/yaml.js");
           ╵     ~~~~~~~~~~~~~~~~~~~~~~~~
✘ [ERROR] Invalid command: on-resolve [plugin JavaScript plugins]
    node_modules/esbuild/lib/main.js:728:12:
      728 │       throw new Error(`Invalid command: ` + request.command);
          ╵             ^
   at handleRequest .handleRequest (/Users/ryota.murakami/laststance/nsx/node_modules/esbuild/lib/main.js:728:13 undefined)
   at handleIncomingPacket .handleIncomingPacket (/Users/ryota.murakami/laststance/nsx/node_modules/esbuild/lib/main.js:745:7 undefined)
   at Socket.readFromStdout (/Users/ryota.murakami/laststance/nsx/node_modules/esbuild/lib/main.js:673:7 undefined)
   at Socket.emit (node:events:513:28 undefined)
   at addChunk .addChunk (node:internal/streams/readable:324:12 undefined)
   at readableAddChunk .readableAddChunk (node:internal/streams/readable:297:9 undefined)
   at Readable.push (node:internal/streams/readable:234:10 undefined)
   at Pipe.onStreamRead (node:internal/stream_base_commons:190:23 undefined)
  The plugin "JavaScript plugins" was triggered by this import
    node_modules/react-syntax-highlighter/dist/esm/async-languages/prism.js:1381:4:
      1381 │     "refractor/lang/yang.js");
           ╵     ~~~~~~~~~~~~~~~~~~~~~~~~
✘ [ERROR] Invalid command: on-resolve [plugin JavaScript plugins]
    node_modules/esbuild/lib/main.js:728:12:
      728 │       throw new Error(`Invalid command: ` + request.command);
          ╵             ^
   at handleRequest .handleRequest (/Users/ryota.murakami/laststance/nsx/node_modules/esbuild/lib/main.js:728:13 undefined)
   at handleIncomingPacket .handleIncomingPacket (/Users/ryota.murakami/laststance/nsx/node_modules/esbuild/lib/main.js:745:7 undefined)
   at Socket.readFromStdout (/Users/ryota.murakami/laststance/nsx/node_modules/esbuild/lib/main.js:673:7 undefined)
   at Socket.emit (node:events:513:28 undefined)
   at addChunk .addChunk (node:internal/streams/readable:324:12 undefined)
   at readableAddChunk .readableAddChunk (node:internal/streams/readable:297:9 undefined)
   at Readable.push (node:internal/streams/readable:234:10 undefined)
   at Pipe.onStreamRead (node:internal/stream_base_commons:190:23 undefined)
  The plugin "JavaScript plugins" was triggered by this import
    node_modules/react-syntax-highlighter/dist/esm/async-languages/prism.js:1386:4:
      1386 │     "refractor/lang/zig.js");

```

[![](https://img.shields.io/badge/Formatted%20by-https%3A%2F%2Fst.elmah.io-%230da58e)](https://st.elmah.io)

**To Reproduce**
1. install `https://volta.sh/` for sync node/yarn version
1. go to https://github.com/laststance/nsx
1. `git clone https://github.com/laststance/nsx.git`
1.  `cd nsx`
1.  `yarn install`
1.  `yarn validate`
1. `yarn storybook`

**Expected behavior**
Show components instead error messages.

**Screenshots**

<img width="1583" alt="Screenshot 2023-06-08 at 12 13 25" src="https://github.com/react-syntax-highlighter/react-syntax-highlighter/assets/5501268/b53b6b70-bbd5-41a7-8a59-cfd732424c22">

========================

**Desktop (please complete the following information):**
- System:
    OS: macOS 13.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.29 GB / 16.00 GB
    Shell: 3.6.1 - /usr/local/bin/fish
- Browsers:
   Chrome: 114.0.5735.106
 - Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.6.0 - ~/.volta/tools/image/npm/9.6.0/bin/npm
- npmPackages:
    react-syntax-highlighter: ^15.5.0 => 15.5.0
    @storybook/addon-essentials: ^7.0.18 => 7.0.18 
    @storybook/addon-interactions: ^7.0.18 => 7.0.18 
    @storybook/addon-links: ^7.0.18 => 7.0.18 
    @storybook/blocks: ^7.0.12 => 7.0.18 
    @storybook/react: ^7.0.18 => 7.0.18 
    @storybook/react-vite: ^7.0.18 => 7.0.18 
    @storybook/testing-library: ^0.1.0 => 0.1.0 

**Additional context**
`yarn build-storybook` is working fine.

**Comment by ryota-murakami** [comment]
This is turn out from https://github.com/storybookjs/storybook/issues/22661

**Comment by longzheng** [comment]
I also get the same issue in `vite` without storybook.

```
[vite] ✘ [ERROR] Invalid command: on-resolve [plugin JavaScript plugins]
[vite] 
[vite]     node_modules/esbuild/lib/main.js:728:12:
[vite]       728 │       throw new Error(`Invalid command: ` + request.command);
[vite]           ╵             ^
[vite] 
[vite]     at handleRequest (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:728:13)
[vite]     at handleIncomingPacket (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:745:7)
[vite]     at Socket.readFromStdout (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:673:7)
[vite]     at Socket.emit (node:events:513:28)
[vite]     at addChunk (node:internal/streams/readable:324:12)
[vite]     at readableAddChunk (node:internal/streams/readable:297:9)
[vite]     at Readable.push (node:internal/streams/readable:234:10)
[vite]     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[vite] 
[vite]   The plugin "JavaScript plugins" was triggered by this import
[vite] 
[vite]     node_modules/react-syntax-highlighter/dist/esm/async-languages/prism.js:1361:4:
[vite]       1361 │     "refractor/lang/xml-doc.js");
[vite]            ╵     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
[vite] 
[vite] ✘ [ERROR] Invalid command: on-resolve [plugin JavaScript plugins]
[vite] 
[vite]     node_modules/esbuild/lib/main.js:728:12:
[vite]       728 │       throw new Error(`Invalid command: ` + request.command);
[vite]           ╵             ^
[vite] 
[vite]     at handleRequest (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:728:13)
[vite]     at handleIncomingPacket (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:745:7)
[vite]     at Socket.readFromStdout (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:673:7)
[vite]     at Socket.emit (node:events:513:28)
[vite]     at addChunk (node:internal/streams/readable:324:12)
[vite]     at readableAddChunk (node:internal/streams/readable:297:9)
[vite]     at Readable.push (node:internal/streams/readable:234:10)
[vite]     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[vite] 
[vite]   The plugin "JavaScript plugins" was triggered by this import
[vite] 
[vite]     node_modules/react-syntax-highlighter/dist/esm/async-languages/prism.js:1366:4:
[vite]       1366 │     "refractor/lang/xojo.js");
[vite]            ╵     ~~~~~~~~~~~~~~~~~~~~~~~~
[vite] 
[vite] ✘ [ERROR] Invalid command: on-resolve [plugin JavaScript plugins]
[vite] 
[vite]     node_modules/esbuild/lib/main.js:728:12:
[vite]       728 │       throw new Error(`Invalid command: ` + request.command);
[vite]           ╵             ^
[vite] 
[vite]     at handleRequest (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:728:13)
[vite]     at handleIncomingPacket (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:745:7)
[vite]     at Socket.readFromStdout (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:673:7)
[vite]     at Socket.emit (node:events:513:28)
[vite]     at addChunk (node:internal/streams/readable:324:12)
[vite]     at readableAddChunk (node:internal/streams/readable:297:9)
[vite]     at Readable.push (node:internal/streams/readable:234:10)
[vite]     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[vite] 
[vite]   The plugin "JavaScript plugins" was triggered by this import
[vite] 
[vite]     node_modules/react-syntax-highlighter/dist/esm/async-languages/prism.js:1371:4:
[vite]       1371 │     "refractor/lang/xquery.js");
[vite]            ╵     ~~~~~~~~~~~~~~~~~~~~~~~~~~
[vite] 
[vite] ✘ [ERROR] Invalid command: on-resolve [plugin JavaScript plugins]
[vite] 
[vite]     node_modules/esbuild/lib/main.js:728:12:
[vite]       728 │       throw new Error(`Invalid command: ` + request.command);
[vite]           ╵             ^
[vite] 
[vite]     at handleRequest (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:728:13)
[vite]     at handleIncomingPacket (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:745:7)
[vite]     at Socket.readFromStdout (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:673:7)
[vite]     at Socket.emit (node:events:513:28)
[vite]     at addChunk (node:internal/streams/readable:324:12)
[vite]     at readableAddChunk (node:internal/streams/readable:297:9)
[vite]     at Readable.push (node:internal/streams/readable:234:10)
[vite]     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[vite] 
[vite]   The plugin "JavaScript plugins" was triggered by this import
[vite] 
[vite]     node_modules/react-syntax-highlighter/dist/esm/async-languages/prism.js:1376:4:
[vite]       1376 │     "refractor/lang/yaml.js");
[vite]            ╵     ~~~~~~~~~~~~~~~~~~~~~~~~
[vite] 
[vite] ✘ [ERROR] Invalid command: on-resolve [plugin JavaScript plugins]
[vite] 
[vite]     node_modules/esbuild/lib/main.js:728:12:
[vite]       728 │       throw new Error(`Invalid command: ` + request.command);
[vite]           ╵             ^
[vite] 
[vite]     at handleRequest (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:728:13)
[vite]     at handleIncomingPacket (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:745:7)
[vite]     at Socket.readFromStdout (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:673:7)
[vite]     at Socket.emit (node:events:513:28)
[vite]     at addChunk (node:internal/streams/readable:324:12)
[vite]     at readableAddChunk (node:internal/streams/readable:297:9)
[vite]     at Readable.push (node:internal/streams/readable:234:10)
[vite]     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[vite] 
[vite]   The plugin "JavaScript plugins" was triggered by this import
[vite] 
[vite]     node_modules/react-syntax-highlighter/dist/esm/async-languages/prism.js:1381:4:
[vite]       1381 │     "refractor/lang/yang.js");
[vite]            ╵     ~~~~~~~~~~~~~~~~~~~~~~~~
[vite] 
[vite] ✘ [ERROR] Invalid command: on-resolve [plugin JavaScript plugins]
[vite] 
[vite]     node_modules/esbuild/lib/main.js:728:12:
[vite]       728 │       throw new Error(`Invalid command: ` + request.command);
[vite]           ╵             ^
[vite] 
[vite]     at handleRequest (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:728:13)
[vite]     at handleIncomingPacket (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:745:7)
[vite]     at Socket.readFromStdout (/Users/long/Documents/GitHub/tap-ui/node_modules/esbuild/lib/main.js:673:7)
[vite]     at Socket.emit (node:events:513:28)
[vite]     at addChunk (node:internal/streams/readable:324:12)
[vite]     at readableAddChunk (node:internal/streams/readable:297:9)
[vite]     at Readable.push (node:internal/streams/readable:234:10)
[vite]     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[vite] 
[vite]   The plugin "JavaScript plugins" was triggered by this import
[vite] 
[vite]     node_modules/react-syntax-highlighter/dist/esm/async-languages/prism.js:1386:4:
[vite]       1386 │     "refractor/lang/zig.js");
[vite]            ╵     ~~~~~~~~~~~~~~~~~~~~~~~
[vite] 
```

However retrying a few times seems to work eventually, which leads me to believe there's some sort of randomness or race condition triggering the issue.

**Comment by AntJanus** [comment]
Having an identical issue. It goes away when downgrading to Vite `4.1.5`. Not using Storybook either.

**Comment by lucperkins** [comment]
I'm also getting this with Vite 4.4.8
